services:
  frontend:
    container_name: portafolio-frontend
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://jorge.adsoproject.dev
    restart:
      - always
    networks:
      - proxy-network


networks:
  proxy-network:
    external: true