name: portafolio-jorge

services:
  frontend:
    container_name: portafolio-jorge-frontend
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://jorge.adsoproject.dev
    restart: always
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true